In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("Final_Jobs_Dataset.csv")

In [5]:
df.head(3)

,job_id,title,company,category,job_type,location,description,description_length,salary_raw,is_salary_provided,...,apply_domain,tags,source,has_email_in_desc,has_link_in_desc,has_phone_in_desc,suspicious_keywords_flag,salary_min,salary_max,is_remote
0,1919265.0,Senior Independent Software Developer,A.Team,Software Development,contract,"Americas, Europe, Israel","<p style=""text-size-adjust: 100%; overflow-wra...",9638,$90 - $150 /hour,1.0,...,remotive.com,"go, wordpress, chat, apple, testing, catalyst",remotive,0,1,0,0,NaN,NaN,NaN
1,1919266.0,Senior Independent AI Engineer / Architect,A.Team,Software Development,contract,"Americas, Europe, Israel","<p class=""my-2 [&amp;+p]:mt-4 [&amp;_strong:ha...",21832,$120 - $170 /hour,1.0,...,remotive.com,"go, UI/UX, wordpress, chat, apple, testing, ca...",remotive,0,1,1,0,NaN,NaN,NaN
2,2088653.0,Sr. Firmware Engineer,Sanctuary Computer,Software Development,contract,Worldwide,"<p style=""--tw-border-spacing-x: 0; --tw-borde...",69748,$150k - $200k,1.0,...,remotive.com,"AWS, C, C++, cloud, UI/UX, open source, produc...",remotive,0,1,0,0,NaN,NaN,NaN

In [6]:
df.shape

(2662, 24)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2662 entries, 0 to 2661
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   job_id                    119 non-null    float64
 1   title                     2661 non-null   object
 2   company                   2661 non-null   object
 3   category                  24 non-null     object
 4   job_type                  1133 non-null   object
 5   location                  2583 non-null   object
 6   description               2601 non-null   object
 7   description_length        2662 non-null   int64
 8   salary_raw                20 non-null     object
 9   is_salary_provided        1563 non-null   float64
 10  company_logo              24 non-null     object
 11  posted_date               2448 non-null   object
 12  days_since_posted         1349 non-null   float64
 13  apply_url                 2662 non-null   object
 14  apply_domain              2662 non-null   object
 15  tags                      1109 non-null   object
 16  source                    2662 non-null   object
 17  has_email_in_desc         2662 non-null   int64
 18  has_link_in_desc          2662 non-null   int64
 19  has_phone_in_desc         2662 non-null   int64
 20  suspicious_keywords_flag  2662 non-null   int64
 21  salary_min                230 non-null    float64
 22  salary_max                230 non-null    float64
 23  is_remote                 1638 non-null   object
dtypes: float64(5), int64(5), object(14)
memory usage: 499.2+ KB

In [8]:
df.isnull().sum()

job_id                      2543
title                          1
company                        1
category                    2638
job_type                    1529
location                      79
description                   61
description_length             0
salary_raw                  2642
is_salary_provided          1099
company_logo                2638
posted_date                  214
days_since_posted           1313
apply_url                      0
apply_domain                   0
tags                        1553
source                         0
has_email_in_desc              0
has_link_in_desc               0
has_phone_in_desc              0
suspicious_keywords_flag       0
salary_min                  2432
salary_max                  2432
is_remote                   1024
dtype: int64

In [9]:
# null values in percentage
df.isnull().sum() / df.shape[0] * 100

job_id                      95.529677
title                        0.037566
company                      0.037566
category                    99.098422
job_type                    57.438017
location                     2.967693
description                  2.291510
description_length           0.000000
salary_raw                  99.248685
is_salary_provided          41.284748
company_logo                99.098422
posted_date                  8.039068
days_since_posted           49.323817
apply_url                    0.000000
apply_domain                 0.000000
tags                        58.339594
source                       0.000000
has_email_in_desc            0.000000
has_link_in_desc             0.000000
has_phone_in_desc            0.000000
suspicious_keywords_flag     0.000000
salary_min                  91.359880
salary_max                  91.359880
is_remote                   38.467318
dtype: float64

### Handle Missing Values

In [10]:
# drop job_id -> unique indentifier,      apply_url -> too unique
df.drop(["job_id", "apply_url"], axis=1, inplace= True)

In [11]:
# company_logo -> most job don't have logo
df['has_logo'] = df['company_logo'].notnull().astype(int)

In [12]:
df.drop('company_logo', axis=1, inplace=True)

In [13]:
# salary missing -> very common in scams
df['has_salary'] = df['salary_raw'].notnull().astype(int)

df.drop(['salary_raw','salary_min','salary_max'], axis=1, inplace=True)

In [14]:
df.drop('is_salary_provided', axis=1, inplace=True )

In [15]:
# fill category with unknown
df['category'] = df['category'].fillna('Unknown')

In [16]:
df['tags']= df['tags'].fillna('')

In [17]:
df['job_type'] = df['job_type'].fillna('Unknown')

In [18]:
df['days_since_posted'] = df['days_since_posted'].fillna(df['days_since_posted'].median())

df['is_remote'] = df['is_remote'].fillna(0)

In [19]:
# drop title & company null value
df = df.dropna(subset=['title', 'company'])

In [20]:
# fill null values
df['location'] = df['location'].fillna('Unknown')

df['description'] = df['description'].fillna('')

In [21]:
df['posted_date'] = pd.to_datetime(df['posted_date'], errors='coerce')

df['posted_date'] = df['posted_date'].fillna(method='ffill')

In [22]:
# create columns
df['missing_count'] = df.isnull().sum(axis = 1)

In [23]:
df['text'] = df['title'] + " " + df['description'] + " " + df['tags']

In [24]:
df.isnull().sum()

title                       0
company                     0
category                    0
job_type                    0
location                    0
description                 0
description_length          0
posted_date                 0
days_since_posted           0
apply_domain                0
tags                        0
source                      0
has_email_in_desc           0
has_link_in_desc            0
has_phone_in_desc           0
suspicious_keywords_flag    0
is_remote                   0
has_logo                    0
has_salary                  0
missing_count               0
text                        0
dtype: int64

In [25]:
kaggle_df = pd.read_csv(r"D:\datasets\Datasets\fake_job_postings.csv")

In [26]:
kaggle_df.head(3)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0

In [27]:
kaggle_df.shape

(17880, 18)

In [28]:
kaggle_df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [29]:
kaggle_df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [30]:
####  Handle null values   ####

In [31]:
kaggle_df.drop(['job_id', 'department'], axis=1, inplace=True)

In [32]:
kaggle_df['description'].fillna('', inplace=True)
kaggle_df['company_profile'].fillna('', inplace=True)
kaggle_df['requirements'].fillna('', inplace=True)
kaggle_df['benefits'].fillna('', inplace=True)

In [33]:
kaggle_df['employment_type'].fillna('Unknown', inplace=True)
kaggle_df['required_experience'].fillna('Unknown', inplace=True)
kaggle_df['required_education'].fillna('Unknown', inplace=True)
kaggle_df['industry'].fillna('Unknown', inplace=True)
kaggle_df['function'].fillna('Unknown', inplace=True)
kaggle_df['location'].fillna('Unknown', inplace=True)

In [34]:
###  create same features  ###

In [35]:
kaggle_df['has_salary'] = kaggle_df['salary_range'].notnull().astype(int)
kaggle_df.drop('salary_range', axis=1, inplace=True)

In [36]:
kaggle_df['text'] = (
    kaggle_df['title'] + " " +
    kaggle_df['description'] + " " +
    kaggle_df['company_profile'] + " " +
    kaggle_df['requirements']
)

In [37]:
kaggle_df['has_logo'] = kaggle_df['has_company_logo']
kaggle_df.drop('has_company_logo', axis=1, inplace=True)

In [38]:
kaggle_df['is_remote'] = kaggle_df['telecommuting']
kaggle_df.drop('telecommuting', axis=1, inplace=True)

In [39]:
kaggle_df['description_length'] = kaggle_df['description'].apply(len)

In [40]:
kaggle_df['job_type'] = kaggle_df['employment_type']

In [41]:
kaggle_df['company'] = kaggle_df['company_profile']

In [42]:
kaggle_df['has_email_in_desc'] = 0
kaggle_df['has_link_in_desc'] = 0
kaggle_df['has_phone_in_desc'] = 0
kaggle_df['apply_domain'] = 'unknown'
kaggle_df['source'] = 'kaggle'
kaggle_df['tags'] = ''
kaggle_df['missing_count'] = 0

In [43]:
kaggle_df.head(3)

,title,location,company_profile,description,requirements,benefits,has_questions,employment_type,required_experience,required_education,...,description_length,job_type,company,has_email_in_desc,has_link_in_desc,has_phone_in_desc,apply_domain,source,tags,missing_count
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,,0,Other,Internship,Unknown,...,905,Other,"We're Food52, and we've created a groundbreaki...",0,0,0,unknown,kaggle,,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,Full-time,Not Applicable,Unknown,...,2077,Full-time,"90 Seconds, the worlds Cloud Video Production ...",0,0,0,unknown,kaggle,,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,,0,Unknown,Unknown,Unknown,...,355,Unknown,Valor Services provides Workforce Solutions th...,0,0,0,unknown,kaggle,,0

In [44]:
kaggle_df.columns

Index(['title', 'location', 'company_profile', 'description', 'requirements',
       'benefits', 'has_questions', 'employment_type', 'required_experience',
       'required_education', 'industry', 'function', 'fraudulent',
       'has_salary', 'text', 'has_logo', 'is_remote', 'description_length',
       'job_type', 'company', 'has_email_in_desc', 'has_link_in_desc',
       'has_phone_in_desc', 'apply_domain', 'source', 'tags', 'missing_count'],
      dtype='object')

In [45]:
# seperate features and taget which is useful for this project
features = ['has_salary', 'text', 'has_logo', 'is_remote', 'description_length', 'has_email_in_desc', 'has_link_in_desc', 'has_phone_in_desc']
target = 'fraudulent'

In [46]:
### train test split ###

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x = kaggle_df[features]
y = kaggle_df['fraudulent']

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 42, stratify=y)

In [50]:
## convert text -> numbers  by providing weight

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

x_train_text = vectorizer.fit_transform(x_train['text'])
x_test_text = vectorizer.transform(x_test['text'])

In [52]:
import numpy as np

num_features = [
    'has_salary','has_logo','is_remote',
    'description_length','has_email_in_desc',
    'has_link_in_desc','has_phone_in_desc'
]

X_train_final = np.hstack((
    x_train_text.toarray(),
    x_train[num_features].values
))

X_test_final = np.hstack((
    x_test_text.toarray(),
    x_test[num_features].values
))

### Train Model

In [53]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_final, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test_final)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9544183445190156

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98      3403
           1       0.52      0.92      0.66       173

    accuracy                           0.95      3576
   macro avg       0.76      0.94      0.82      3576
weighted avg       0.97      0.95      0.96      3576


Confusion Matrix:
 [[3254  149]
 [  14  159]]

In [55]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train_final, y_train)

y_pred_rf = rf.predict(X_test_final)

In [56]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(x_train_text, y_train)   # Only text features

y_pred_nb = nb.predict(x_test_text)

In [57]:
# XGBoost

from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(X_train_final, y_train)

y_pred_xgb = xgb.predict(X_test_final)

In [58]:
# model comparison

from sklearn.metrics import classification_report

print("Logistic Regression:\n", classification_report(y_test, y_pred))
print("Random Forest:\n", classification_report(y_test, y_pred_rf))
print("Naive Bayes:\n", classification_report(y_test, y_pred_nb))
print("XGBoost:\n", classification_report(y_test, y_pred_xgb))

Logistic Regression:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98      3403
           1       0.52      0.92      0.66       173

    accuracy                           0.95      3576
   macro avg       0.76      0.94      0.82      3576
weighted avg       0.97      0.95      0.96      3576

Random Forest:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3403
           1       1.00      0.61      0.76       173

    accuracy                           0.98      3576
   macro avg       0.99      0.81      0.88      3576
weighted avg       0.98      0.98      0.98      3576

Naive Bayes:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      3403
           1       0.98      0.29      0.45       173

    accuracy                           0.97      3576
   macro avg       0.97      0.64      0.71      3576
weighted avg       0.97      0.97      0.96      3576

XGBoost:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      3403
           1       0.98      0.74      0.84       173

    accuracy                           0.99      3576
   macro avg       0.98      0.87      0.92      3576
weighted avg       0.99      0.99      0.99      3576

In [59]:
## Improve F1 score

y_prob = model.predict_proba(X_test_final)[:, 1]

y_pred_new = (y_prob > 0.45).astype(int)

In [71]:
# final evaluation
print(classification_report(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97      3403
           1       0.46      0.95      0.62       173

    accuracy                           0.94      3576
   macro avg       0.73      0.95      0.80      3576
weighted avg       0.97      0.94      0.95      3576

In [60]:
# save logistic Regression model

import pickle

pickle.dump(model, open('final_model.pkl', 'wb'))
pickle.dump(vectorizer, open('vectorizer.pkl', 'wb'))

In [61]:
# load model & vectorizer

model = pickle.load(open('final_model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

In [62]:
num_features = [
    'has_salary','has_logo','is_remote',
    'description_length','has_email_in_desc',
    'has_link_in_desc','has_phone_in_desc'
]

In [63]:
for col in num_features:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df[num_features] = df[num_features].fillna(0)

In [64]:
# text vectorization
X_api_text = vectorizer.transform(df['text'])

In [65]:
# combine features
X_api_final = np.hstack((
    X_api_text.toarray(),
    df[num_features].values
))

In [66]:
print(np.array(X_api_final).dtype)

float64

In [67]:
# predict scam/real
df['predicted_scam'] = model.predict(X_api_final)

In [68]:
df['scam_probability'] = model.predict_proba(X_api_final)[:,1]

In [69]:
df['scam_percentage'] = (df['scam_probability'] * 100).round(2)

In [70]:
# df.to_csv('predicted_jobs.csv', index=False)

In [71]:
import zipfile
with zipfile.ZipFile("cleaned_data.zip",'w') as z:
    z.write("predicted_jobs.csv",
           arcname = "predicted_jobs.csv")

print("zip file created successfully")

zip file created successfully